### ISSUE TITLE
Glyphicons not showing up

### ISSUE THREAD

**Issue by mauckc** [ShinkaiSetsuna/oboeru#1]
bootswatch line below required for glyphicons 

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css">
```

This line seems to work alongside the imported library in use:
```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
```

try adding the former to the <head> in the template.html or a test index.html

**Comment by DeanShin** [comment]
Glyphicons were removed in bootstrap 4.0.0, adding the previous link seems to fix it. In the future, possibly use different icon set
